CREATE TABLE [dbo].[iO_Client_IndividualEmployment]
(
[CED_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CED_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CED_IDLink_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_IDLink_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_IDLink_CMR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_IDLink_XCEt] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_IDLink_StreetType_C] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_IDLink_Country_C] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_IDLink_Occupation_C] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_IDLink_StreetType_P] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_IDLink_Country_P] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_SeqNumber] [bigint] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[CED_Type] [int] NULL,
[CED_IDUser] [int] NULL,
[CED_EmployerName_C] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_TimeInServiceY_C] [int] NULL,
[CED_PropertyName_C] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_UnitNumber_C] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_StreetNumber_C] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_StreetName_C] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_City_C] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_State_C] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_PostCode_C] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_SuiteNumber_C] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_FloorNumber_C] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_ContactNumber_C] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_TimeInServiceM_C] [int] NULL,
[CED_TimeInIndustryM_C] [int] NULL,
[CED_TimeInIndustryY_C] [int] NULL,
[CED_EmployerName_P] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_TimeInServiceY_P] [int] NULL,
[CED_PropertyName_P] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_UnitNumber_P] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_StreetNumber_P] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_StreetName_P] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_City_P] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_State_P] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_PostCode_P] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_TimeInServiceM_P] [int] NULL,
[CED_ContactNumber_P] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_StartDate] [smalldatetime] NULL,
[CED_EndDate] [smalldatetime] NULL,
[CED_PrimaryEmployment] [bit] NULL,
[CED_SelfEmployed] [bit] NULL,
[CED_CurrentEmployment] [bit] NULL,
[CED_OnProbation] [bit] NULL,
[CED_PoorEmployment] [bit] NULL,
[CED_PEGAAcceptable] [bit] NULL,
[CED_EmploymentType] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_Verification_ContactDetails] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_Verification_DateVerified] [datetime] NULL,
[CED_Verification_EmployerPhone] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_Verification_EmployerPhoneAreaCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_Verification_EmployerPhoneISD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_VerificationName] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_Verified] [bit] NULL,
[CED_HighRisk] [bit] NULL,
[CED_HighRiskOverride] [bit] NULL,
[CED_Note] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_Verification_EmployerFax] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_Verification_EmployerFaxAreaCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_Verification_EmployerFaxISD] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_Verification_EmployerEmail] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_Verification_EmployerPhoneISDMob] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_Verification_EmployerPhoneMob] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_JobTitle] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_IDLink_XCI] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_Verification_EmployerPhoneExtension] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_TimeInServiceTot_C] [int] NULL,
[CED_TimeInIndustryTot_C] [int] NULL,
[CED_TypeOfBusiness] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_EmployeePerformance] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_SalaryDeductionAvailable] [int] NULL,
[CED_HoursPerWeek] [int] NULL,
[CED_EmployeeID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_EmployeeAttention] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_EmployeePayDay] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_EmployeeNextPayDate] [datetime] NULL,
[CED_IndustryType] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_Area_C] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_Area_P] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_StartDate_P] [smalldatetime] NULL,
[CED_EndDate_P] [smalldatetime] NULL,
[CED_UnemployedReason] [int] NULL,
[CED_SelfEmployedIncome] [money] NULL,
[CED_SelfEmployedIncomePeriodY] [int] NULL,
[CED_SelfEmployedIncomePeriodM] [int] NULL,
[CED_ContractorTimeInContract] [int] NULL,
[CED_ContractorTermOfContractLeft] [int] NULL,
[CED_ContractorTradingHistY] [int] NULL,
[CED_ContractorTradingHistM] [int] NULL,
[CED_ContractorExperienceY] [int] NULL,
[CED_ContractorExperienceM] [int] NULL,
[CED_EmploymentBase] [int] NULL,
[CED_EmploymentClass] [int] NULL,
[CED_EmployerName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_EmployerTOB] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_EmployerAddress] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_EmployerContactName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_EmployerContactDetail] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_SelfEmployedType] [int] NULL,
[CED_SelfEmployedCompanyName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_SelfEmployedCompanyAddress] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_SelfEmployedTOB] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_SelfEmployedShareHolding] [float] NULL,
[CED_SelfEmployedAccName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_SelfEmployedAccAddress] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_SelfEmployedAccContact] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_SelfEmployedAccNumber] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_ContractorCompanyName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_ContractorLTDName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_ContractorLTDNumber] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_ContractorFirmName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_ContractorFirmAddress] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_ContractorFirmREFName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CED_ContractorFirmREFNumber] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[iO_Client_IndividualEmployment] ADD CONSTRAINT [PK_iO_CLient_EmploymentDetail] PRIMARY KEY CLUSTERED  ([CED_ID]) WITH (FILLFACTOR=85) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_iO_Client_IndividualEmployment] ON [dbo].[iO_Client_IndividualEmployment] ([CED_IDLink_CMR]) WITH (FILLFACTOR=85) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', N'Primary Key.', 'SCHEMA', N'dbo', 'TABLE', N'iO_Client_IndividualEmployment', 'COLUMN', N'CED_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Used to compare records in Replication process.', 'SCHEMA', N'dbo', 'TABLE', N'iO_Client_IndividualEmployment', 'COLUMN', N'CED_IDLink_Version'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Redundant.', 'SCHEMA', N'dbo', 'TABLE', N'iO_Client_IndividualEmployment', 'COLUMN', N'CED_Ownership'
GO
