CREATE TABLE [dbo].[iO_MOR_CustomerVersions]
(
[MORcv_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_Ownership] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_Version] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_Sync] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_Code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_IDLink_MORreq] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_CORRESPONDENCELANGUAGE] [int] NULL,
[MORcv_DATEOFBIRTH] [smalldatetime] NULL,
[MORcv_TITLE] [int] NULL,
[MORcv_CUSTOMERNUMBER] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_SURNAME] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_FIRSTFORENAME] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_SECONDFORENAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_OTHERFORENAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_CORRESPONDENCENAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_CUSTOMERROLETYPE] [int] NULL,
[MORcv_UPDATEFLAG] [int] NULL,
[MORcv_OWNERROLEINRELATIONSHIP] [int] NULL,
[MORcv_MEMBEROFSTAFF] [bit] NULL,
[MORcv_LENDERREFERENCE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_CONTACTEMAILADDRESS1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_CONTACTEMAILADDRESS2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_SOCIALINSURANCENUMBER] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORcv_MARITALSTATUS] [int] NULL,
[MORcv_NUMBEROFDEPENDENTS] [tinyint] NULL,
[MORcv_CARESIDENTINDICATOR] [bit] NULL,
[MORcv_RESIDENTTYPE] [int] NULL,
[MORcv_REPORTDATE] [smalldatetime] NULL,
[MORcv_BEACONSCORE] [smallint] NULL,
[MORcv_TERMHISTORY] [smallint] NULL,
[MORcv_TOTALBALANCES] [decimal] (18, 0) NULL,
[MORcv_TMTHLYPYMNTS] [decimal] (18, 0) NULL,
[MORcv_NUMBEROFR0] [smallint] NULL,
[MORcv_NUMBEROFI0] [smallint] NULL,
[MORcv_NUMBEROFO0] [smallint] NULL,
[MORcv_NUMBEROFM0] [smallint] NULL,
[MORcv_NUMBEROFR1] [smallint] NULL,
[MORcv_NUMBEROFI1] [smallint] NULL,
[MORcv_NUMBEROFO1] [smallint] NULL,
[MORcv_NUMBEROFM1] [smallint] NULL,
[MORcv_NUMBEROFR2] [smallint] NULL,
[MORcv_NUMBEROFI2] [smallint] NULL,
[MORcv_NUMBEROFO2] [smallint] NULL,
[MORcv_NUMBEROFM2] [smallint] NULL,
[MORcv_NUMBEROFR3] [smallint] NULL,
[MORcv_NUMBEROFI3] [smallint] NULL,
[MORcv_NUMBEROFO3] [smallint] NULL,
[MORcv_NUMBEROFM3] [smallint] NULL,
[MORcv_NUMBEROFR4] [smallint] NULL,
[MORcv_NUMBEROFI4] [smallint] NULL,
[MORcv_NUMBEROFO4] [smallint] NULL,
[MORcv_NUMBEROFM4] [smallint] NULL,
[MORcv_NUMBEROFR5] [smallint] NULL,
[MORcv_NUMBEROFI5] [smallint] NULL,
[MORcv_NUMBEROFO5] [smallint] NULL,
[MORcv_NUMBEROFM5] [smallint] NULL,
[MORcv_NUMBEROFR6] [smallint] NULL,
[MORcv_NUMBEROFI6] [smallint] NULL,
[MORcv_NUMBEROFO6] [smallint] NULL,
[MORcv_NUMBEROFM6] [smallint] NULL,
[MORcv_NUMBEROFR7] [smallint] NULL,
[MORcv_NUMBEROFI7] [smallint] NULL,
[MORcv_NUMBEROFO7] [smallint] NULL,
[MORcv_NUMBEROFM7] [smallint] NULL,
[MORcv_NUMBEROFR8] [smallint] NULL,
[MORcv_NUMBEROFI8] [smallint] NULL,
[MORcv_NUMBEROFO8] [smallint] NULL,
[MORcv_NUMBEROFM8] [smallint] NULL,
[MORcv_NUMBEROFR9] [smallint] NULL,
[MORcv_NUMBEROFI9] [smallint] NULL,
[MORcv_NUMBEROFO9] [smallint] NULL,
[MORcv_NUMBEROFM9] [smallint] NULL,
[MORcv_BANKRUPTCY] [smallint] NULL,
[MORcv_BNKRPTPROP] [smallint] NULL,
[MORcv_LEGALITEMS] [smallint] NULL,
[MORcv_COLLECTIONS] [smallint] NULL,
[MORcv_GARNISH] [smallint] NULL,
[MORcv_AKAREFERENCE] [smallint] NULL,
[MORcv_INVALIDSIN] [smallint] NULL,
[MORcv_SUFUNEQUAL] [smallint] NULL,
[MORcv_SINMISMATCH] [smallint] NULL,
[MORcv_DOBMISMATCH] [smallint] NULL,
[MORcv_CDATAEXISTS] [bit] NULL,
[MORcv_ENCODE] [int] NULL,
[MORcv_COMPRESSION] [int] NULL,
[MORcv_HTMLREPORT] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
