CREATE TABLE [dbo].[iO_Product_CommissionImport]
(
[RCMi_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RCMi_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_IDLink_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_IDLink_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_IDLink_RMR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_IDLink_Type] [int] NULL,
[RCMi_IDLink_Note] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_SeqNumber] [bigint] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[RCMi_LoanID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_AccountNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_ProductType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_LoanType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_BankName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_OriginatorID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_OriginatorName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_OriginatorContact] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_SubOriginatorID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_SubOriginatorName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_SubOriginatorContact] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_Consultant] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_FullName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_Surname1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_Surname2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_FirstName2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_BorrowerPCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_InterestRate] [money] NULL,
[RCMi_InvestLoanRate] [money] NULL,
[RCMi_AdvancedAmt] [money] NULL,
[RCMi_SettlementDate] [datetime] NULL,
[RCMi_DischargeDate] [datetime] NULL,
[RCMi_PrincipalBalanceStart] [money] NULL,
[RCMi_PrincipalBalanceEnd] [money] NULL,
[RCMi_OffsetBalance] [money] NULL,
[RCMi_AvailableCredit] [money] NULL,
[RCMi_SRVDueFrom] [datetime] NULL,
[RCMi_SRVDueTo] [datetime] NULL,
[RCMi_StartDate] [datetime] NULL,
[RCMi_EndDate] [datetime] NULL,
[RCMi_Days] [int] NULL,
[RCMi_CommissionRate] [money] NULL,
[RCMi_CommissionEarned] [money] NULL,
[RCMi_CommissionWithheld] [money] NULL,
[RCMi_ReasonWithheld] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_CommissionPaid] [money] NULL,
[RCMi_GST] [money] NULL,
[RCMi_SRVMarginAsPercent] [money] NULL,
[RCMi_SRVMarginAsAmt] [money] NULL,
[RCMi_ArrearsOLDays] [int] NULL,
[RCMi_LMIProvider] [varchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_FeeFreeRate] [money] NULL,
[RCMi_OtherFeeRate] [money] NULL,
[RCMi_PenaltyRate] [money] NULL,
[RCMi_Currency] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RCMi_RepayFreq] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[iO_Product_CommissionImport] ADD CONSTRAINT [PK_iO_Product_CommissionImport] PRIMARY KEY CLUSTERED  ([RCMi_ID]) WITH (FILLFACTOR=85) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', N'Primary Key.', 'SCHEMA', N'dbo', 'TABLE', N'iO_Product_CommissionImport', 'COLUMN', N'RCMi_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Redundant.', 'SCHEMA', N'dbo', 'TABLE', N'iO_Product_CommissionImport', 'COLUMN', N'RCMi_Ownership'
GO
