CREATE TABLE [dbo].[iO_Product_LoanMDT]
(
[RLM_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RLM_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RLM_IDLink_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_IDLink_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_IDLink_RMR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_IDLink_XRPu] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_IDLink_XRTu] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_IDLink_XRPy] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_IDLink_CBD] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_IDLink_PErc] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_IDLink_XRDr] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_IDLink_XRPlc] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_IDLink_SplitType] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_SeqNumber] [bigint] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[RLM_SeqGroup] [bigint] NULL,
[RLM_Type] [int] NULL,
[RLM_IDUser] [int] NULL,
[RLM_Term_Years] [int] NULL,
[RLM_Term_Month] [int] NULL,
[RLM_Term_Days] [int] NULL,
[RLM_Arrears_Days] [int] NULL,
[RLM_Payment_Method] [int] NULL,
[RLM_Repayment_Opt_F] [bit] NULL,
[RLM_Repayment_Opt_M] [bit] NULL,
[RLM_RepaymentFreq] [int] NULL,
[RLM_InterestOnly_Opt] [bit] NULL,
[RLM_TypeOfInterest] [int] NULL,
[RLM_LodgementType] [int] NULL,
[RLM_LastStatementNumber] [int] NULL,
[RLM_PreApproval] [bit] NULL,
[RLM_Credit_LVR] [float] NULL,
[RLM_Note] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_ProductFeaturePYA] [bit] NULL,
[RLM_ProductFeatureRDW] [bit] NULL,
[RLM_ProductFeatureADP] [bit] NULL,
[RLM_ProductFeatureIAP] [bit] NULL,
[RLM_ProductFeatureCB] [bit] NULL,
[RLM_ProductFeatureLOC] [bit] NULL,
[RLM_ProductFeatureCC] [bit] NULL,
[RLM_DD_Formula] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_ExistingMortgage] [bit] NULL,
[RLM_Insured] [bit] NULL,
[RLM_IDLink_InterestType] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_IDLink_InterestCompound] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_IDLink_LoanType] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_MIPremiumAmount] [float] NULL,
[RLM_MIPremiumPST] [float] NULL,
[RLM_IDLink_MortgageType] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_PandIPaymentAmount] [float] NULL,
[RLM_PandIPaymentAmountMonthly] [float] NULL,
[RLM_IDLink_PaymentFrequency] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_IDLink_PaymentTerms] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_Rate_NetRate] [float] NULL,
[RLM_Refi_BlendedAmortization] [bit] NULL,
[RLM_Rate_Requested] [float] NULL,
[RLM_IDLink_SingleProgressiveType] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_PandIPaymentAmountQualify] [float] NULL,
[RLM_QualifyingGDS] [float] NULL,
[RLM_Rate_Qualify] [float] NULL,
[RLM_QualifyingTDS] [float] NULL,
[RLM_QualifyDetail_AmortizationTerm] [float] NULL,
[RLM_IDLink_QualifyDetail_InterestCompound] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_IDLink_DealType] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_FCXDeal_LegacyAppRef] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_FCXDeal_LegacyOfficeID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_FCXDeal_LegacySystem] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_FCXDeal_LegacyUserID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_FCXDeal_RefinanceImporovementAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_FCXDeal_RefinanceImprovementDesc] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_FCXDeal_RefinanceImprovementFlag] [bit] NULL,
[RLM_FCXDeal_RefinancePurpose] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_FCXDeal_TaxPayor] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_FCXDeal_ThirdPartyAppFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_FCXDeal_LenderCommissionCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_FCXDeal_LenderForceDupSubFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_FCXDeal_MultiProject] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_FCXDeal_ProprietairePlusLOC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_TotalDownPayment] [float] NULL,
[RLM_LastStatementDate] [datetime] NULL,
[RLM_FCXDeal_RefiPurpose] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_FurtherInformation] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_InformationReceived] [bit] NULL,
[RLM_EffRateForBuyDowns] [float] NULL,
[RLM_M3_OldProdLastPayMeth] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_SchedulePaymentOption] [int] NULL,
[RLM_DD_CustomerNominatedAmt] [float] NULL,
[RLM_DD_CustomerNominatedVariable] [float] NULL,
[RLM_SubInc] [int] NULL,
[RLM_OriginatorConsent] [bit] NULL,
[RLM_Payment_Current_Fixed] [float] NULL,
[RLM_DD_Amount] [float] NULL,
[RLM_IDLink_XSCa] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_InterestOnly_Term_Years] [int] NULL,
[RLM_Fixed_Term_Years] [int] NULL,
[RLM_IDLink_SourceOfDeposit] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_PurposeExplanation] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLM_IDLink_XRPu_L1] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[iO_Product_LoanMDT] ADD CONSTRAINT [PK_iO_Product_LoanMDT] PRIMARY KEY CLUSTERED  ([RLM_ID]) WITH (FILLFACTOR=85) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_iO_Product_LoanMDT] ON [dbo].[iO_Product_LoanMDT] ([RLM_IDLink_RMR]) WITH (FILLFACTOR=85) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_DEBUG_dta_index_iO_Product_LoanMDT_25_772249856__K5_K1_6_16_78] ON [dbo].[iO_Product_LoanMDT] ([RLM_IDLink_RMR], [RLM_ID]) WITH (FILLFACTOR=85) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', N'Primary Key.', 'SCHEMA', N'dbo', 'TABLE', N'iO_Product_LoanMDT', 'COLUMN', N'RLM_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Used to compare records in Replication process.', 'SCHEMA', N'dbo', 'TABLE', N'iO_Product_LoanMDT', 'COLUMN', N'RLM_IDLink_Version'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Redundant.', 'SCHEMA', N'dbo', 'TABLE', N'iO_Product_LoanMDT', 'COLUMN', N'RLM_Ownership'
GO
