CREATE TABLE [dbo].[iO_Product_LoanAssetPropertyMortgage]
(
[RLAPm_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RLAPm_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_IDLink_RLAp] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_IDLink_Holder] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_IDLink_XMT] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_IDLink_XRPM] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_Amount] [float] NULL,
[RLAPm_DeedOfPriority] [bit] NULL,
[RLAPm_BMSAmount] [float] NULL,
[RLAPm_SubsequentType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_Notes] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_IDLink_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_IDLink_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_IDUser] [int] NULL,
[RLAPm_Type] [int] NULL,
[RLAPm_SeqNumber] [bigint] NULL,
[RLAPm_FCXActualPaymentTerm] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXAdditionalPrincipal] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXAdminFee] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXAffiliationProgram] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXAmortTerm] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXBalanceRemaining] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXCashBackAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXCashBackOverride] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXCashBackPercentage] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXCurrentMtgNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXEffectiveAmort] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXExistingMtgFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXExistingMtgHolder] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXFirstPamentDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXInsuredFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXInterestAdjustAmout] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXInterestAdjustDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXInterestCompound] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXInterestOnlyFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXRepaymentType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXInterestType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXLenderSubLanguage] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXLenderSubLenderName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXLenderSubLenderCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXLenderSubLenderLinkID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXLenderSubLenderRegistrationName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXLenderSubUseLegacyUserID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXLenderOriginatorNotes] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXLenderRoutingReceiver] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXLenderRoutingSender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXLenderSubmitRequestTime] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXLineOfBusiness] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXLoanType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXLOCRepaymentType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXLTV] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXMarketSubmission] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXMarketSubmissionNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXMaturityDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXMIFeeAmount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXMIPremiumAmount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXMIPremiumPST] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXMIReferenceNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXMortgageInsurerID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXMortgageType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXMtgInsIncludeFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXMtgProdMPBusinessID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXMtgProductID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXMtgProvderID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXNetLoanAmount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXOriginalMtgAmount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXPAndIPaymentAmount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXPAndIPaymentAmountMonthly] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXPaymentFrequency] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXPaymentTerm] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXPayOffType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXPricingRateInvIndexEffDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXRateInterestRage] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXRateDiscount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXRatePremium] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXRateBuydownRate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXRateNetRate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXRateGuaranteeLength] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXRefiAdditionalInfo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXRefiBlendedAmort] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXRequestedRate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXPrivilegePayment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXPrepaymentOptions] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXSingleProgressiveType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXTotalLoanAmount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXPAndIPaymentAmountQualify] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXQualifyingGDS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXQualifyingRate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXQualifyingTDS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXQualifyingDetailAmortTerm] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXQualifyingDetailInterestCompound] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXQualifyingDetailInterestOnlyFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXQualifyingDetailRepaymentType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_ExistingMortgageNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_FCXTermType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAPm_BrokerModel] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[iO_Product_LoanAssetPropertyMortgage] ADD CONSTRAINT [PK_iO_Product_LoanAssetPropertyMortgage] PRIMARY KEY CLUSTERED  ([RLAPm_ID]) WITH (FILLFACTOR=85) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_iO_Product_LoanAssetPropertyMort_10] ON [dbo].[iO_Product_LoanAssetPropertyMortgage] ([RLAPm_IDLink_RLAp], [RLAPm_FCXPayOffType]) WITH (FILLFACTOR=85) ON [PRIMARY]
GO
