CREATE TABLE [dbo].[iO_Product_SecurityPTY_Log]
(
[RSP_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RSP_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RSP_IDLink_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_RMR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_RSE] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_CAD] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_StreetType] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_Country] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTy] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTu] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTt] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTp] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTgt] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTgc] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTht] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTus] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTul] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTc] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTz] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_SeqNumber] [bigint] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[RSP_Type] [int] NULL,
[RSP_IDUser] [int] NULL,
[RSP_PurchasePrice] [float] NULL,
[RSP_EstimatedValue] [float] NULL,
[RSP_PropertyName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_UnitNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_StreetNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_StreetName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_City] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_State] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_PostCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_Direction] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_ActionType] [int] NULL,
[RSP_AccessName] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_AccessNumberWork] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_AccessNumberHome] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_AccessNumberMobile] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_AccessNote] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_NameOnDeed] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_BookNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_CertID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_CT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_FolioNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_LotNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_LpDp] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_Parish] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_County] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_SubDiv] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_VolNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_TenantName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_GrossWeeklyRent] [float] NULL,
[RSP_RegistrationNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_DateRegistered] [datetime] NULL,
[RSP_StampedTo] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_AccessNumber] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_DateDischarged] [datetime] NULL,
[RSP_PropertyZoning] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_CurrentMarketValue] [float] NULL,
[RSP_AccessContactType] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_InactiveSecurity] [bit] NULL,
[RSP_LandSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_StudioSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_EstRentalValue] [float] NULL,
[RSP_LandValue] [float] NULL,
[RSP_ValuationPostcode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_BedroomCount] [int] NULL,
[RSP_BathroomCount] [int] NULL,
[RSP_KitchenCount] [int] NULL,
[RSP_FloorCount] [int] NULL,
[RSP_UnitCount] [int] NULL,
[RSP_HeatingValue] [float] NULL,
[RSP_HeatingType] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IsServiceOrManaged] [bit] NULL,
[RSP_SuiteNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_FloorNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_HighRisk] [bit] NULL,
[RSP_HighRiskOverride] [bit] NULL,
[RSP_LocationTypeCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_BuilderName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_FeesIncludeHeatFlag] [bit] NULL,
[RSP_IncludesTDS] [bit] NULL,
[RSP_InsulatedWithUFFI] [bit] NULL,
[RSP_LegalLine1] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_LegalLine2] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_LegalLine3] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_MLSListing] [bit] NULL,
[RSP_Note] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTvi] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTro] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTs] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTw] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRTl] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XRPT] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IsPrimary] [bit] NULL,
[RSP_AppraisalRequested] [bit] NULL,
[RSP_AppraisalDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_AgeOfStructure] [int] NULL,
[RSP_SubjectProperty] [bit] NULL,
[RSP_YearBuilt] [int] NULL,
[RSP_TaxationYear] [int] NULL,
[RSP_OriginalPurchasePrice] [float] NULL,
[RSP_OriginalPurchaseDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_AnnualIncomeAmt] [float] NULL,
[RSP_IncomeDesc] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IncomePctGDS] [float] NULL,
[RSP_IncomePctTDS] [float] NULL,
[RSP_IDLink_XFR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IDLink_XIN] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_IncomeAmt] [float] NULL,
[RSP_FISBO] [bit] NULL,
[RSP_EnvironmentalRisk] [int] NULL,
[RSP_IsEnergyEfficient] [bit] NULL,
[RSP_PurchaseLtv] [float] NULL,
[RSP_OriginalLtv] [float] NULL,
[RSP_FireInsuranceNo] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_TitleInsuranceNo] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_PreviousSaleDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_FireInsuranceExpiryDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_FireInsuranceCompany] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_TitleInsuranceCompany] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSP_StateRegion] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Modified Date] [datetime] NULL,
[User ID] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[iO_Product_SecurityPTY_Log] ADD CONSTRAINT [PK_iO_Product_SceurityPTY_Log] PRIMARY KEY CLUSTERED  ([RSP_ID]) WITH (FILLFACTOR=85) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', N'Primary Key.', 'SCHEMA', N'dbo', 'TABLE', N'iO_Product_SecurityPTY_Log', 'COLUMN', N'RSP_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Used to compare records in Replication process.', 'SCHEMA', N'dbo', 'TABLE', N'iO_Product_SecurityPTY_Log', 'COLUMN', N'RSP_IDLink_Version'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Redundant.', 'SCHEMA', N'dbo', 'TABLE', N'iO_Product_SecurityPTY_Log', 'COLUMN', N'RSP_Ownership'
GO
