CREATE TABLE [dbo].[iO_FCX_ApplicantGroup_Applicant]
(
[FCXaa_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FCXaa_IDLink_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_IDLink_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_IDLink_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_IDLink_Code] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_IDLink_SCM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_IDLink_FCXa] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_SeqNumber] [bigint] NOT NULL IDENTITY(1, 1),
[FCXaa_DOB] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_Email] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_Language] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_MaritalStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_Salutation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_MiddleName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_Suffix] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_NumberOfDependants] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_PreferredContactMethod] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_SocialInsuranceNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_Solicitation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_BankruptcyStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_CitizenshipType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_ClientReferenceNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_CreditScore] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_EmployeeNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_ExistingClient] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_FirstTimeBuyer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_Gender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_IsEmployee] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_PairOrder] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_PrimaryApplicationFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_RelationshipToApplicant] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXaa_Smoker] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
