CREATE TABLE [dbo].[iO_Product_LoanAssetProperty]
(
[RLAp_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RLAp_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RLAp_IDLink_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_RMR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RLAp_IDLink_CMR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAP_IDLink_StreetType] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_Country] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_EstimatedValue] [float] NULL,
[RLAp_PropertyName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_UnitNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_StreetNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_StreetName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_Direction] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_City] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_State] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_PostCode] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_SeqNumber] [bigint] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[RLAp_ProprietorName] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_PurchasedDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_RegisteredProprietor] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_OccupancyFCXID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTy] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTu] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTt] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTp] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTgt] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTgc] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTht] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTus] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTul] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTc] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTvi] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTro] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTz] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTs] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTw] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRTl] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XRPT] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_Type] [int] NULL,
[RLAp_IDUser] [int] NULL,
[RLAp_PurchasePrice] [float] NULL,
[RLAp_ActionType] [int] NULL,
[RLAp_AccessName] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_AccessNumberWork] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_AccessNumberHome] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_AccessNumberMobile] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_AccessNote] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_NameOnDeed] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_BookNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_CertID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_CT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_FolioNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_LotNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_LpDp] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_Parish] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_County] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_SubDiv] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_VolNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_TenantName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_GrossWeeklyRent] [float] NULL,
[RLAp_RegistrationNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_DateRegistered] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_StampedTo] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_AccessNumber] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_DateDischarged] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_PropertyZoning] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_CurrentMarketValue] [float] NULL,
[RLAp_AccessContactType] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_InactiveSecurity] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_LandSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_StudioSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_EstRentalValue] [float] NULL,
[RLAp_LandValue] [float] NULL,
[RLAp_ValuationPostcode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_BedroomCount] [int] NULL,
[RLAp_BathroomCount] [int] NULL,
[RLAp_KitchenCount] [int] NULL,
[RLAp_FloorCount] [int] NULL,
[RLAp_UnitCount] [int] NULL,
[RLAp_HeatingValue] [float] NULL,
[RLAp_HeatingType] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IsServiceOrManaged] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_SuiteNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_FloorNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_HighRisk] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_HighRiskOverride] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_LocationTypeCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_BuilderName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_FeesIncludeHeatFlag] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IncludesTDS] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_InsulatedWithUFFI] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_LegalLine1] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_LegalLine2] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_LegalLine3] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_MLSListing] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_Note] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IsPrimary] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_AppraisalRequested] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_AgeOfStructure] [int] NULL,
[RLAp_SubjectProperty] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_YearBuilt] [int] NULL,
[RLAp_TaxationYear] [int] NULL,
[RLAp_OriginalPurchasePrice] [float] NULL,
[RLAp_OriginalPurchaseDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_AnnualIncomeAmt] [float] NULL,
[RLAp_IncomeDesc] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IncomePctGDS] [float] NULL,
[RLAp_IncomePctTDS] [float] NULL,
[RLAp_IDLink_XFR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IDLink_XIN] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RLAp_IncomeAmt] [float] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[iO_Product_LoanAssetProperty] ADD CONSTRAINT [PK_iO_Product_LoanAssetProperty] PRIMARY KEY CLUSTERED  ([RLAp_ID]) WITH (FILLFACTOR=85) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_iO_Product_LoanAssetProperty_10] ON [dbo].[iO_Product_LoanAssetProperty] ([RLAp_IDLink_RMR], [RLAp_ID]) WITH (FILLFACTOR=85) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', N'Primary Key.', 'SCHEMA', N'dbo', 'TABLE', N'iO_Product_LoanAssetProperty', 'COLUMN', N'RLAp_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Used to compare records in Replication process.', 'SCHEMA', N'dbo', 'TABLE', N'iO_Product_LoanAssetProperty', 'COLUMN', N'RLAp_IDLink_Version'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Redundant.', 'SCHEMA', N'dbo', 'TABLE', N'iO_Product_LoanAssetProperty', 'COLUMN', N'RLAp_Ownership'
GO
