CREATE TABLE [dbo].[tblExploreMtgAppEOD20110615d]
(
[MtgAppID] [decimal] (18, 0) NULL,
[OriginatorID] [decimal] (18, 0) NULL,
[MtgAppStatusNum] [decimal] (18, 0) NULL,
[MtgAppStatusCode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UWUserID] [decimal] (18, 0) NULL,
[IsPreapproval] [bit] NULL,
[IsArchivedPreapproval] [bit] NULL,
[OrigConditionsOutstanding] [int] NULL,
[TotConditionsOutstanding] [int] NULL,
[DaysUntilClose] [int] NULL,
[ApplicationID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApplicationDate] [datetime] NULL,
[TotalLoanAmount] [decimal] (18, 0) NULL,
[AmortizationTerm] [int] NULL,
[EstimatedClosingDate] [datetime] NULL,
[DealTypeID] [int] NULL,
[LenderProfileID] [decimal] (18, 0) NULL,
[SourceApplicationID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DealPurposeID] [int] NULL,
[SourceSystemMailBoxNbr] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LoanToValue] [decimal] (18, 0) NULL,
[MITypeID] [int] NULL,
[ReferenceDealNumber] [int] NULL,
[ReferenceDealTypeID] [int] NULL,
[TotalPurchasePrice] [decimal] (18, 0) NULL,
[PostedInterestRate] [int] NULL,
[UnderWriterUserID] [int] NULL,
[EstimatedPaymentAmount] [int] NULL,
[PandIPaymentAmount] [decimal] (18, 0) NULL,
[EscrowPaymentAmount] [int] NULL,
[MIPremiumAmount] [decimal] (18, 0) NULL,
[NetLoanAmount] [decimal] (18, 0) NULL,
[StatusDate] [datetime] NULL,
[Discount] [float] NULL,
[SecondaryFinancing] [int] NULL,
[DenialReasonID] [int] NULL,
[RenewalOptionsID] [int] NULL,
[NetInterestRate] [decimal] (18, 0) NULL,
[RateDate] [int] NULL,
[BuyDownRate] [float] NULL,
[SpecialFeatureID] [int] NULL,
[InterimInterestAmount] [int] NULL,
[DownPaymentAmount] [decimal] (18, 0) NULL,
[MortgageInsurerID] [int] NULL,
[MtgProdID] [int] NULL,
[MIPolicyNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstPaymentDate] [datetime] NULL,
[NetPaymentAmount] [int] NULL,
[MILoanNumber] [int] NULL,
[MaturityDate] [datetime] NULL,
[CommitmentIssueDate] [datetime] NULL,
[CommitmentAcceptDate] [int] NULL,
[RefExistingMtgNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CombinedTotalLiabilities] [decimal] (18, 0) NULL,
[BankABANumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankAccountNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankName] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActualClosingDate] [datetime] NULL,
[CombinedTotalAssets] [decimal] (18, 0) NULL,
[CombinedTotalIncome] [decimal] (18, 0) NULL,
[CombinedTDS] [decimal] (18, 0) NULL,
[CombinedGDS] [decimal] (18, 0) NULL,
[RenewalDate] [int] NULL,
[NumberOfBorrowers] [int] NULL,
[NumberOfGuarantors] [int] NULL,
[ServicingMortgageNumber] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaymentTermID] [int] NULL,
[InterestTypeID] [int] NULL,
[PaymentFrequencyID] [int] NULL,
[PrepaymentOptionsID] [int] NULL,
[RateFormulaID] [int] NULL,
[StatusID] [int] NULL,
[RiskRatingID] [int] NULL,
[ElectronicSystemSource] [int] NULL,
[CommitmentExpirationDate] [datetime] NULL,
[RequestedSolicitorName] [int] NULL,
[RequestedAppraisorName] [int] NULL,
[BranchProfileID] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InterestAdjustmentDate] [datetime] NULL,
[PrivilegePaymentID] [int] NULL,
[AdvanceHold] [int] NULL,
[ClientNumber] [int] NULL,
[CombinedLTV] [numeric] (18, 0) NULL,
[CombinedTotAnnualHeatingExp] [decimal] (18, 0) NULL,
[CombinedTotAnnualTaxExp] [decimal] (18, 0) NULL,
[CombinedTotCondoFeeExp] [decimal] (18, 0) NULL,
[CombinedTotPropertyExp] [decimal] (18, 0) NULL,
[CommitmentPeriod] [int] NULL,
[CommitmentProduced] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DatePreAppFirm] [int] NULL,
[FinanceProgramID] [int] NULL,
[MIPayorID] [int] NULL,
[NewMoney] [int] NULL,
[NextRateChangeDate] [int] NULL,
[NumberOfProperties] [int] NULL,
[OldMoney] [int] NULL,
[OnHoldDate] [int] NULL,
[PreApproval] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Premium] [float] NULL,
[RateLock] [int] NULL,
[RateLockExpirationDate] [int] NULL,
[RateLockPeriod] [int] NULL,
[RefiCurrentBal] [int] NULL,
[RemainingBalanceSecondaryFin] [int] NULL,
[ReturnDate] [int] NULL,
[TaxPayorID] [int] NULL,
[TotalActAppraisedValue] [decimal] (18, 0) NULL,
[TotalEstAppraisedValue] [decimal] (18, 0) NULL,
[TotalPropertyExpenses] [decimal] (18, 0) NULL,
[AdditionalPrincipal] [int] NULL,
[TotalPaymentAmount] [decimal] (18, 0) NULL,
[ActualPaymentTerm] [int] NULL,
[CombinedGDSBorrower] [int] NULL,
[CombinedTDSBorrower] [int] NULL,
[CombinedGDS3Year] [int] NULL,
[CombinedTDS3Year] [int] NULL,
[CombinedEquityAvailable] [int] NULL,
[EffectiveAmortizationMonths] [int] NULL,
[PostedRate] [decimal] (18, 0) NULL,
[BlendedRate] [int] NULL,
[ChannelMedia] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClosingTypeID] [int] NULL,
[MIUpfront] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreapprovalConclusionDate] [datetime] NULL,
[PreapprovalOriginalOfferDate] [datetime] NULL,
[PreviouslyDeclined] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RequiredDownPayment] [decimal] (18, 0) NULL,
[MIIndicatorID] [int] NULL,
[RepaymentTypeID] [int] NULL,
[DecisionModificationTypeID] [int] NULL,
[ScenarioApproved] [int] NULL,
[ScenarioRecommended] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScenarioNumber] [int] NULL,
[ScenarioDescription] [int] NULL,
[MIComments] [int] NULL,
[MIStatusID] [int] NULL,
[SystemTypeID] [int] NULL,
[TotalFeeAmount] [decimal] (18, 0) NULL,
[MaximumLoanAmount] [int] NULL,
[ScenarioLocked] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalLoanBridgeAmount] [int] NULL,
[SolicitorSpecialInstructions] [int] NULL,
[CombinedLendingValue] [decimal] (18, 0) NULL,
[ExistingLoanAmount] [int] NULL,
[GDSTDS3YearRate] [decimal] (18, 0) NULL,
[MaximumPrincipalAmount] [int] NULL,
[MaximumTDSExpensesAllowed] [int] NULL,
[MICommunicationFlag] [int] NULL,
[MIExistingPolicyNumber] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MinimumIncomeRequired] [int] NULL,
[PAPurchasePrice] [decimal] (18, 0) NULL,
[InstructionProduced] [int] NULL,
[TeaserDiscount] [int] NULL,
[TeaserMaturityDate] [int] NULL,
[TeaserNetInterestRate] [int] NULL,
[TeaserPIAmount] [int] NULL,
[TeaserTerm] [int] NULL,
[CopyType] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OpenMIResponseFlag] [int] NULL,
[ResolutionConditionID] [int] NULL,
[MIPremiumPST] [decimal] (18, 0) NULL,
[PandIPaymentAmountMonthly] [decimal] (18, 0) NULL,
[FirstPaymentDateMonthly] [datetime] NULL,
[ProgressAdvance] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdvanceToDateAmount] [decimal] (18, 0) NULL,
[AdvanceNumber] [int] NULL,
[MIRUIntervention] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RefiPurpose] [int] NULL,
[RefiOrigPurchasePrice] [decimal] (18, 0) NULL,
[RefiBlendedAmortization] [int] NULL,
[RefiOrigMTGAmount] [int] NULL,
[RefiImprovementsDesc] [int] NULL,
[RefiImprovementAmount] [int] NULL,
[NextAdvanceAmount] [decimal] (18, 0) NULL,
[RefiOrigPurchaseDate] [int] NULL,
[RefiCurMortgageHolder] [int] NULL,
[ResubmissionFlag] [int] NULL,
[MIPolicyNumCMHC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MIPolicyNumGE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MCCMarketType] [int] NULL,
[IncomeVerificationTypeID] [int] NULL,
[RateCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductDescription] [varchar] (90) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerFirstName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerMiddleInitial] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerLastName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstTimeBuyer] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerBirthDate] [datetime] NULL,
[NSfocCurrencyTypeID] [int] NULL,
[SalutationID] [int] NULL,
[MaritalStatusID] [int] NULL,
[SocialInsuranceNumber] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerHomePhoneNumber] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerWorkPhoneNumber] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerFaxNumber] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerEmailAddress] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientReferenceNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumberOfDependents] [int] NULL,
[NumberOfTimesBankrupt] [int] NULL,
[RaceID] [int] NULL,
[CreditScore] [int] NULL,
[GDS] [int] NULL,
[TDS] [int] NULL,
[EducationLevelID] [int] NULL,
[NetWorth] [float] NULL,
[ExistingClient] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditSummary] [int] NULL,
[LanguagePreferenceID] [int] NULL,
[BorrowerGeneralStatusID] [int] NULL,
[BorrowerTypeID] [int] NULL,
[CitizenshipTypeID] [int] NULL,
[TotalAssetAmount] [decimal] (18, 0) NULL,
[TotalLiabilityAmount] [decimal] (18, 0) NULL,
[PaymentHistoryTypeID] [int] NULL,
[TotalIncomeAmount] [decimal] (18, 0) NULL,
[DateOfCreditBureauProfile] [datetime] NULL,
[CreditBureauOnFileDate] [datetime] NULL,
[BureauAttachment] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExistingClientComments] [int] NULL,
[BankruptcyStatusID] [int] NULL,
[Age] [int] NULL,
[StaffOfLender] [int] NULL,
[StaffType] [int] NULL,
[TotalLiabilityPayments] [decimal] (18, 0) NULL,
[GDS3Year] [int] NULL,
[TDS3Year] [int] NULL,
[BorrowerWorkPhoneExtension] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BorrowerGenderID] [int] NULL,
[SmokeStatusID] [int] NULL,
[DisabilityStatusID] [int] NULL,
[LifeStatusID] [int] NULL,
[GuarantorOtherLoans] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StreetTypeID] [int] NULL,
[P_PropertyTypeID] [int] NULL,
[P_PropertyUsageID] [int] NULL,
[DwellingStyleID] [int] NULL,
[OccupancyTypeID] [int] NULL,
[PropertyStreetNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyStreetName] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyAddressLine2] [int] NULL,
[PropertyCity] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyPostalFSA] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PropertyPostalLDU] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LegalLine1] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LegalLine2] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LegalLine3] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YearBuilt] [int] NULL,
[ProvinceID] [int] NULL,
[PurchasePrice] [decimal] (18, 0) NULL,
[MunicipalityID] [int] NULL,
[UnitNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LotSize] [int] NULL,
[NumberOfUnits] [int] NULL,
[PropertyLocationID] [int] NULL,
[StreetDirectionID] [int] NULL,
[LivingSpace] [int] NULL,
[LivingSpaceUnitOfMeasureID] [int] NULL,
[DwellingTypeID] [int] NULL,
[LendingValue] [decimal] (18, 0) NULL,
[MLSListingFlag] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SolicitorName] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SolicitorFirm] [int] NULL,
[SourceOfBusinessProfileID] [decimal] (18, 0) NULL,
[AdminUserID] [int] NULL,
[DBDUserID] [int] NULL,
[PropertyUsageID] [int] NULL,
[PropertyTypeID] [int] NULL,
[OriginalMortgageNumber] [int] NULL,
[LineOfBusinessID] [int] NULL,
[MarsNameSearch] [int] NULL,
[MarsPropertySearch] [int] NULL,
[CommisionAmount] [int] NULL,
[InterestCompoundID] [int] NULL,
[InvestorProfileID] [int] NULL,
[SecondApproverID] [int] NULL,
[JointApproverID] [int] NULL,
[SourceFirmProfileID] [int] NULL,
[GroupProfileID] [int] NULL,
[AdministratorID] [int] NULL,
[PricingProfileID] [int] NULL,
[RefinanceNewMoney] [int] NULL,
[CrossSellProfileID] [int] NULL,
[FifthApproverID] [int] NULL,
[FinalApproverID] [int] NULL,
[FourthApproverID] [int] NULL,
[InvestorApproved] [int] NULL,
[InvestorConfirmationNumber] [int] NULL,
[LienHolderSecondaryFinancing] [int] NULL,
[LienPositionID] [int] NULL,
[SecondaryFinancingLienHolder] [int] NULL,
[SourceRefAppNbr] [int] NULL,
[ThirdApproverID] [int] NULL,
[ApprovalTypeID] [int] NULL,
[CheckNotesFlag] [int] NULL,
[ClosingDatePlus90Days] [int] NULL,
[PerdiemInterestAmount] [int] NULL,
[IADNumberOfDays] [int] NULL,
[FunderProfileID] [int] NULL,
[PrequalificationMICertNum] [int] NULL,
[BrokerCommPaid] [int] NULL,
[HoldReasonID] [int] NULL,
[PmntPlusLifeDisability] [int] NULL,
[LifePremium] [int] NULL,
[DisabilityPremium] [int] NULL,
[CombinedPremium] [int] NULL,
[InterestRateIncrement] [int] NULL,
[InterestRateIncLifeDisability] [int] NULL,
[EquivalentInterestRate] [int] NULL,
[CommisionCode] [int] NULL,
[MultiProject] [int] NULL,
[ProprietairePlus] [int] NULL,
[ProprietairePlusLoc] [int] NULL,
[SourceApplicationVersion] [int] NULL,
[AddCreditCostInsIncurred] [int] NULL,
[TotalCreditCost] [int] NULL,
[IntWithoutInsCreditCost] [int] NULL,
[UploadSerialNumber] [int] NULL,
[FundingUploadDone] [int] NULL,
[InsuranceProportionsID] [int] NULL,
[LifePercentCoverageReq] [int] NULL,
[DisPercentCoverageReq] [int] NULL,
[HeatTypeID] [int] NULL,
[NumberOfBedrooms] [int] NULL,
[InsulatedWithUffi] [int] NULL,
[MonthlyCondoFees] [int] NULL,
[LandValue] [int] NULL,
[PropertyValueSource] [int] NULL,
[AppraisalSourceID] [int] NULL,
[EquityAvailable] [int] NULL,
[NewConstructionID] [int] NULL,
[UrbanSuburban] [int] NULL,
[EstimatedAppraisalValue] [int] NULL,
[ActualAppraisalValue] [int] NULL,
[PrimaryPropertyFlag] [int] NULL,
[AprraisalDateAct] [int] NULL,
[LotSizeDepth] [int] NULL,
[LotSizeFrontage] [int] NULL,
[LotSizeUnitOfMeasureID] [int] NULL,
[PropertyOccurenceNumber] [int] NULL,
[PropertyReferenceNumber] [int] NULL,
[SewageTypeID] [int] NULL,
[WaterTypeID] [int] NULL,
[StructureAge] [int] NULL,
[P_TotalPropertyExpenses] [int] NULL,
[TotalAnnualTaxAmount] [int] NULL,
[Zoning] [int] NULL,
[GarageSizeID] [int] NULL,
[GarageTypeID] [int] NULL,
[BuilderName] [int] NULL
) ON [PRIMARY]
GO
