CREATE TABLE [dbo].[v_RUBIOverview]
(
[RUBINumber] [bigint] NULL,
[DealID] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Borrower] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Brand] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purpose] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Broker] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lender] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Insurer] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Underwriter] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LTV] [float] NULL,
[SubmittedRate] [float] NULL,
[NetRate] [float] NULL,
[Discount] [float] NULL,
[Buydown] [float] NULL,
[Premium] [float] NULL,
[IsQuickClose] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsBuydown] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApplicationAmount] [float] NULL,
[BeaconScore] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumberOfApplicants] [int] NULL,
[SecurityProvince] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AmortizationMonths] [int] NULL,
[TermMonths] [int] NULL,
[IsRental] [int] NULL,
[IsBFS] [int] NULL,
[IsHELOC] [int] NULL,
[Is5050] [int] NULL,
[CurrentStatus] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnteredStatus] [datetime] NULL,
[ClosingDate] [datetime] NULL,
[ApplicationDate] [datetime] NULL,
[RateSetDate] [datetime] NULL,
[RUBIParentNumber] [int] NULL,
[IsSubAccount] [int] NULL,
[MaturityDate] [datetime] NULL,
[BrandID] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReviewedTime] [datetime] NULL,
[RefExistingMtgNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
