CREATE TABLE [dbo].[iO_FDI_OmniDetail]
(
[FOd_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FOd_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_IDLink_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_SeqNumber] [bigint] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[FOd_IDLink_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_IDLink_FOm] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_IDLink_RTM] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_RecordSeqNo] [int] NULL,
[FOd_MsgType] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_MsgTypeOrig] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_PANLen] [int] NULL,
[FOd_PAN] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_ProcessCode] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_TranAmtAU] [float] NULL,
[FOd_TranAmtAcqr] [float] NULL,
[FOd_CardHolderAmt] [float] NULL,
[FOd_TransmissionMM] [int] NULL,
[FOd_TransmissionDD] [int] NULL,
[FOd_TransmissionHH] [int] NULL,
[FOd_TransmissionNN] [int] NULL,
[FOd_TransmissionSS] [int] NULL,
[FOd_SysTraceAuditNum] [int] NULL,
[FOd_LocalMM] [int] NULL,
[FOd_LocalDD] [int] NULL,
[FOd_LocalHH] [int] NULL,
[FOd_LocalNN] [int] NULL,
[FOd_LocalSS] [int] NULL,
[FOd_ExpiryYY] [int] NULL,
[FOd_ExpiryMM] [int] NULL,
[FOd_SettlementMM] [int] NULL,
[FOd_SettlementDD] [int] NULL,
[FOd_MerchCatCode] [int] NULL,
[FOd_AcquiringInstCountryCode] [int] NULL,
[FOd_PointOfServiceEntryMode] [int] NULL,
[FOd_CardSeqNo] [int] NULL,
[FOd_POSConditionCode] [int] NULL,
[FOd_AcquirerIDLen] [int] NULL,
[FOd_AcquirerID] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_RetrievalRefNo] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_AuthIDResp] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_RespCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_CardAcceptTerminalID] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_CardAcceptID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_CardAcceptName] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_CardAcceptLocation] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_CardAcceptCountryCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_CashComponentAmt] [float] NULL,
[FOd_TranCurrencyCode] [int] NULL,
[FOd_CardHolderCurrencyCode] [int] NULL,
[FOd_OrigDataElements] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_AccountID1] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_AccountID2] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_IssuerIDLen] [int] NULL,
[FOd_IssuerID] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_MerchStateCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_MerchNo] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_DeviceType] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_AcquirerName] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_IssuerName] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_MerchSettlementOrg] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_AuthCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_CustomerRefData] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_ErrorCode] [int] NULL,
[FOd_ErrorDesc] [varchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FOd_CardAcceptNameLocn] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[iO_FDI_OmniDetail] ADD CONSTRAINT [PK_iO_FDI_OmniDetail] PRIMARY KEY CLUSTERED  ([FOd_ID]) WITH (FILLFACTOR=85) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', N'Primary Key.', 'SCHEMA', N'dbo', 'TABLE', N'iO_FDI_OmniDetail', 'COLUMN', N'FOd_ID'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Used to compare records in Replication process.', 'SCHEMA', N'dbo', 'TABLE', N'iO_FDI_OmniDetail', 'COLUMN', N'FOd_IDLink_Version'
GO
EXEC sp_addextendedproperty N'MS_Description', N'Redundant.', 'SCHEMA', N'dbo', 'TABLE', N'iO_FDI_OmniDetail', 'COLUMN', N'FOd_Ownership'
GO
