CREATE TABLE [dbo].[iO_MOR_CustomerAddresses]
(
[MORca_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORca_Ownership] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORca_Version] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORca_Sync] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORca_Code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORca_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORca_IDLink_MORcv] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORca_ADDRESSTYPE] [int] NULL,
[MORca_DATEMOVEDIN] [smalldatetime] NULL,
[MORca_DATEMOVEDOUT] [smalldatetime] NULL,
[MORca_NATUREOFOCCUPANCY] [int] NULL,
[MORca_INTENTTYPE] [int] NULL,
[MORca_POSTALCODE] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORca_APTORUNITNUMBER] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORca_BUILDINGORHOUSENUMBER] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORca_STREET] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORca_STREETDIRECTION] [int] NULL,
[MORca_STREETTYPE] [int] NULL,
[MORca_RRORPOBOXNUMBER] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORca_TOWN] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORca_PROVINCESEQNO] [int] NULL,
[MORca_COUNTRY] [int] NULL,
[MORca_GROSSINCOME] [decimal] (18, 0) NULL,
[MORca_VACANCYANDBADDEBT] [decimal] (18, 0) NULL,
[MORca_REALTYTAXES] [decimal] (18, 0) NULL,
[MORca_MANAGEMENTEXPENSES] [decimal] (18, 0) NULL,
[MORca_INSURANCE] [decimal] (18, 0) NULL,
[MORca_HYDRO] [decimal] (18, 0) NULL,
[MORca_WATERANDSEWER] [decimal] (18, 0) NULL,
[MORca_CONDOEXPENSES] [decimal] (18, 0) NULL,
[MORca_MORTGAGEPAYMENT] [decimal] (18, 0) NULL,
[MORca_EFFECTIVEGROSSANNUALINCOME] [decimal] (18, 0) NULL,
[MORca_RENTALINCOMEOFFSETPERCENTAGE] [int] NULL,
[MORca_ESTIMATEDCURRENTVALUE] [int] NULL,
[MORca_TENANCYTYPE] [int] NULL
) ON [PRIMARY]
GO
