CREATE TABLE [dbo].[iO_FCX_LifeAndDisability_NonMortgageApplicant]
(
[FCXldn_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FCXldn_IDLink_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_IDLink_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_IDLink_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_IDLink_Code] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_IDLink_SCM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_IDLink_FCXld] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_SeqNumber] [bigint] NOT NULL IDENTITY(1, 1),
[FCXldn_Address_UnitNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_Address_StreetNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_Address_StreetName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_Address_StreetType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_Address_StreetDirection] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_Address_City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_Address_Province] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_Address_InternationalPostalcode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_Address_PostalcodeFSA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_Address_PostalcodeLDU] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_Address_Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_DateOfBirth] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_Email] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_Employer] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_EmploymentYear] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_EmploymentMonth] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_Gender] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_PreferredContact] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_Smoker] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_InsuranceDetails_CoverageType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_InsuranceDetails_InsuranceProportions] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_InsuranceDetails_Amortization] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_InsuranceDetails_InsuredAmount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_InsuranceDetails_TotalLoanAmtExceeded] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_InsuranceDetails_HealthDeclaration_HealthCompleted] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_InsuranceDetails_HealthDeclaration_HealthDeclarationRequired] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_InsuranceDetails_HealthDeclaration_longFormRequired] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_InsuranceDetails_HealthDeclaration_HealthQuestion1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_InsuranceDetails_HealthDeclaration_HealthQuestion2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_InsuranceDetails_HealthDeclaration_HealthQuestion3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXldn_InsuranceDetails_HealthDeclaration_HealthQuestion4] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
