CREATE TABLE [dbo].[iO_FCX_SubjectProperty]
(
[FCXs_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FCXs_IDLink_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_IDLink_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_IDLink_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_IDLink_Code] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_IDLink_SCM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_IDLink_FCXl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_SeqNumber] [bigint] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[FCXs_ActualAppraisalValue] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_Address_UnitNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_Address_StreetNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_Address_StreetName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_Address_StreetType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_Address_StreetDirection] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_Address_City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_Address_Province] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_Address_InternationPostcode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_Address_PostCodeFSA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_Address_PostCodeLDU] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_Address_Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_AppraisalDateAct] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_BuilderName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_DwellingStyle] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_DwellingType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_EstimatedAppraisalValue] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_FeesIncludedInHeat] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_GuarageSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_GuarageType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_HeatType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_IncludesTDS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_RentalIncome_AnnualIncomeAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_RentalIncome_IncomeAmount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_RentalIncome_IncomeDescription] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_RentalIncome_IncomePeriod] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_RentalIncome_IncomeType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_RentalIncome_PercentageGDS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_RentalIncome_PercentageTDS] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_InsulatedWithUffi] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_LegalLine1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_LegalLine2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_LegalLine3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_LivingSpace] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_LivingSpaceUnitMeasure] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_LotSize] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_LotSizeUnitMeasure] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_MLSListingFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_NewConstruction] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_NumberOfUnits] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_OccupancyType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_OriginalPurchasePrice] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_PrimarypropertyFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_PropertyType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_PropertyValueIndex] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_PurchasePrice] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_RefiOrigPurchaseDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_RentalOffsetOption] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_RequestAppraisal] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_SewageType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_StructureAge] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_SubjectPropertyFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_TaxationYear] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_WaterType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXs_YearBuilt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[iO_FCX_SubjectProperty] ADD CONSTRAINT [PK_FCXs_ID] PRIMARY KEY CLUSTERED  ([FCXs_ID]) WITH (FILLFACTOR=85) ON [PRIMARY]
GO
