CREATE TABLE [dbo].[iO_MEM_Application]
(
[MEMapp_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_IDLink_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_IDLink_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_IDLink_CMR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_IDLink_RMR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_ApplyDate] [datetime] NULL,
[MEMapp_LoanAmount] [int] NULL,
[MEMapp_LoanTerm] [int] NULL,
[MEMapp_Title] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_EMailAddress] [varchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_DateOfBirth] [datetime] NULL,
[MEMapp_HomePhone] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_MobilePhone] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_WorkPhone] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_ResidentialStatus] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_PostCode] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_FlatNumber] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_HouseNameOrNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_AddressLine1] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_AddressLine2] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_County] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_EmploymentIndustry] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_CompanyName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_PrimaryIncome] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_PayFrequency] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_NetMonthlyPay] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_NextPayDate] [datetime] NULL,
[MEMapp_DebitCardType] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_DirectDeposit] [bit] NULL,
[MEMapp_BankWith] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_MonthlyRepaymentDay] [int] NULL,
[MEMapp_PersonalData] [bit] NULL,
[MEMapp_Marketing] [bit] NULL,
[MEMapp_SECCI_Date] [datetime] NULL,
[MEMapp_SECCI_Method] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_DirectDebitMandate_Date] [datetime] NULL,
[MEMapp_DirectDebitMandate_Method] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_LoanAgreement_Date] [datetime] NULL,
[MEMapp_LoanAgreement_Method] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_Notes] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MEMapp_Status] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
