CREATE TABLE [dbo].[iO_FCX_Participant]
(
[FCXp_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FCXp_IDLink_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_IDLink_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_IDLink_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_IDLink_Code] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_IDLink_SCM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_IDLink_FCXl] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_SeqNumber] [bigint] NOT NULL IDENTITY(1, 1),
[FCXp_ContactAddress_UnitNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_ContactAddress_StreetNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_ContactAddress_StreetName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_ContactAddress_StreetType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_ContactAddress_StreetDirection] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_ContactAddress_City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_ContactAddress_Province] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_ContactAddress_InternationalPostalcode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_ContactAddress_PostalcodeFSA] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_ContactAddress_PostalcodeLDU] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_ContactAddress_Country] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_ContactEmailAddress] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_Contact_Salutation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_Contact_FirstName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_Contact_MiddleName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_Contact_LastName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_Contact_Language] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_Contact_PreferredContact] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_Notes] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_PartyCompanyName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_PartyType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_BranchLocation] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_BranchTransitNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FCXp_URL] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
