CREATE TABLE [dbo].[iO_EFX_LegalItems]
(
[EFXLEG_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_Code] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_Type] [int] NULL,
[EFXLEG_IDUser] [int] NULL,
[EFXLEG_IDLink_EFXRQ] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_IDLink_CMR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_SeqNumber] [bigint] NOT NULL IDENTITY(1, 1),
[EFXLEG_IDLink_EFXSBJ] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_LegalItem_code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_LegalItem_description] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_DateFiled] [int] NULL,
[EFXLEG_CourtID_CustomerNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_CourtID_Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_CaseNumber] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_Status_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_Status_description] [varchar] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_DateSatisfied] [int] NULL,
[EFXLEG_Amount] [int] NULL,
[EFXLEG_VerificationDate] [int] NULL,
[EFXLEG_Defendant] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_Plaintiff] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_LawyerNameAddress] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_UpdateSource_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_UpdateSource_description] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_NarrativeCode_1] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_NarrativeCode_2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXLEG_Note] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
