CREATE TABLE [dbo].[iO_EFX_Collections]
(
[EFXCOL_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_Code] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_Type] [int] NULL,
[EFXCOL_IDUser] [int] NULL,
[EFXCOL_IDLink_EFXRQ] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_IDLink_CMR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_SeqNumber] [bigint] NOT NULL IDENTITY(1, 1),
[EFXCOL_IDLink_EFXSBJ] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_Collection_code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_Collection_description] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_AssignedDate] [int] NULL,
[EFXCOL_AgencyId_CustomerNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_AgencyId_Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_LedgerNumber] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_CC_AccountNumberAndOrName] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_CCIndustry_code] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_CCIndustry_description] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_Reason_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_Reason_description] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_OriginalAmount] [int] NULL,
[EFXCOL_BalanceAmount] [int] NULL,
[EFXCOL_DateOfLastPayment] [int] NULL,
[EFXCOL_DatePaid] [int] NULL,
[EFXCOL_VerificationDate] [int] NULL,
[EFXCOL_UpdateSource_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_UpdateSource_description] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_NarrativeCode_1] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_NarrativeCode_2] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXCOL_Note] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
