CREATE TABLE [dbo].[iO_Security_MasterReference2]
(
[SMR_ID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SMR_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_IDLink_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_IDLink_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_IDLink_CMR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_IDLink_Profile] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_SeqNumber] [bigint] NULL,
[SMR_Type] [int] NULL,
[SMR_IDUser] [int] NULL,
[SMR_Title] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_Login_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_Password] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_AccessForcePasswordChange] [bit] NULL,
[SMR_Supervisor] [bit] NULL,
[SMR_AccessClient] [bit] NULL,
[SMR_AccessAccount] [bit] NULL,
[SMR_AccessClientCenterNew] [bit] NULL,
[SMR_AccessClientCenterDelete] [bit] NULL,
[SMR_AccessProductCenterNew] [bit] NULL,
[SMR_LocationType] [int] NULL,
[SMR_Action] [int] NULL,
[SMR_Hint] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_DocumentDirectory_Client] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_DocumentDirectory_Product] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_DocumnetDirectory_Template] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_DocumentDirectory_Email] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_SMTPServer] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_POP3Server] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_POP3UserID] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_POP3Pwd] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_Image] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMR_LastLockoutTime] [datetime] NULL,
[SMR_LastPasswordChange] [datetime] NULL,
[SMR_ApplyPasswordPolicy] [bit] NULL,
[SMR_ApprovalLimit] [float] NULL,
[SMR_Note] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[iO_Security_MasterReference2] ADD CONSTRAINT [io_security_masterreference2_PrimaryKey] PRIMARY KEY CLUSTERED  ([SMR_ID]) ON [PRIMARY]
GO
