CREATE TABLE [dbo].[iO_FNF_FileStatus]
(
[FNFfs_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_IDLink_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_IDLink_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_IDLink_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_IDLink_Code] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_IDLink_SCM] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_SeqNumber] [int] NULL,
[FNFfs_FileNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_MortgageNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_Party] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_Province] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_Program] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_Opened] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_Priority] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_Stage] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_InProcess] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_Closing] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_Office] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_SalesContact] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_Funder] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_Underwriter] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_TitleInsurance] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_RegNumber] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_ActivationStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_PropertyAddress] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_PartyAddress] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_LegalProperyDescription] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_FundingStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_FundsRequested] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_Processing] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_Signing] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_Funding] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_Registration] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNFfs_Reporting] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
