CREATE TABLE [dbo].[iO_Product_SecurityPTYMortgage_Component]
(
[RSPmc_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RSPmc_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_IDLink_RSPm] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_SeqNumber] [bigint] NULL,
[RSPmc_AdditionalInfo] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_ComponentType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_FirstPaymentDateLimit] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_InterestOnlyFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_InterestRate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_MtgProd_mpBusninessID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_RepaymentType] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_PricingInventory_IndexEffDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_TeaserMaturityDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_TeaserInterestRate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_TeaserPIAmount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_TeaserRateInterestSaving] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_AdditionalPrincipal] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_AdvanceHold] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_ActualPaymentTerm] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_AmortTerm] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_BalRemainingAtEOT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_BuydownRate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_CashbackAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_CashBackAmtOverride] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_CashBackPercent] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_CommissionCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_Discount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_EffAmortMonths] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_ExistingAccountInd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_ExistingAccountNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_FirstPaymentDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_FirstPaymentDateMonthly] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_IADNumberOfDays] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_InterestAdjustmentAmount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_InterestAdjustmentDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_MaturityDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_MIAllocateFlage] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_MortgageAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_NetInterestRate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_PAndIPaymentAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_PAndIPaymentAmtMonthly] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_PaymentFrequency] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_PerDiemInterestAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_Premium] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_RepaymentOptions] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_PrivilegePayment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_PtyTaxAllocateFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_PtyTaxEscrowAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_RateGuaranteePeriod] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompMtg_TotalMtgAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_AdvanceHold] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_CommissionCode] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_Discount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_ExistingAccInd] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_ExistingAccNo] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_FirstPaymentDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_InterestAdjustmentDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_LOCAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_MIAllocateFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_NetInterestRate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_PAndIPaymentAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_PAndIPaymentAmtMonthy] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_PaymentFrequency] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_Premium] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_PrePaymentOptions] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_PrivilegePayment] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_PtyTaxAllocateFlag] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_PtyTaxEscrowAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLOC_TotalLocAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLoan_ActualPaymentTerm] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLoan_Discount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLoan_FirstPaymentDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLoan_IADNumberOfDays] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLoan_InterestAdjustmentAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLoan_InterestAdjustmentDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLoan_LoanAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLoan_MaturityDate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLoan_NetInterestRate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLoan_PAndIPaymentAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLoan_PAndIPaymentAmtMonthly] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLoan_PaymentFrequency] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLoan_PerDiemInterestAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompLoan_Premium] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompCreditCard_CreditCardAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSPmc_CompOverDraft_OverDraftAmt] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[iO_Product_SecurityPTYMortgage_Component] ADD CONSTRAINT [PK_iO_Product_SecurityPTYMtg_Component] PRIMARY KEY CLUSTERED  ([RSPmc_ID]) WITH (FILLFACTOR=85) ON [PRIMARY]
GO
