CREATE TABLE [dbo].[iO_EFX_TradeLines]
(
[EFXTrd_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_Ownership] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_Version] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_Sync] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_Code] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_Type] [int] NULL,
[EFXTrd_IDUser] [int] NULL,
[EFXTrd_IDLink_EFXRQ] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_SeqNumber] [bigint] NOT NULL IDENTITY(1, 1),
[EFXTrd_IDLink_EFXSBJ] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_DateReported] [int] NULL,
[EFXTrd_CreditorId_CustomerNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_CreditorId_Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_ParsedTelephone_AreaCode] [int] NULL,
[EFXTrd_ParsedTelephone_Number] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_ParsedTelephone_Extension] [int] NULL,
[EFXTrd_AccountNumber] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_AccountNumber_mnemonic] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_Association_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_Association_description] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_HighCreditAmount] [int] NULL,
[EFXTrd_PaymentTermAmount] [int] NULL,
[EFXTrd_BalanceAmount] [int] NULL,
[EFXTrd_PastDueAmount] [int] NULL,
[EFXTrd_pastDuePeriodNumber] [int] NULL,
[EFXTrd_MonthsReviewed] [int] NULL,
[EFXTrd_DateOpened] [int] NULL,
[EFXTrd_DateLastActivityOrPayment] [int] NULL,
[EFXTrd_PortfolioType_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_PortfolioType_description] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_PaymentRate_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_PaymentRate_description] [varchar] (85) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_Status_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_Status_description] [varchar] (85) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_Count30DayPastDue] [int] NULL,
[EFXTrd_Count60DayPastDue] [int] NULL,
[EFXTrd_Count90DayPastDue] [int] NULL,
[EFXTrd_UpdateSource_code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_UpdateSource_description] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFXTrd_Note] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
