CREATE TABLE [dbo].[lc_balance07062013]
(
[Branch] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BranchRefer] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientNo] [bigint] NULL,
[LoanNo] [bigint] NULL,
[PrimaryClient] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LodgeDate] [datetime] NULL,
[SettleDate] [datetime] NULL,
[Prod_Type] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Prod_Status] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProdStat2] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Broker] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Broker Contact] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employer] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[position] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssessorName] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Vendor] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Security] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Make] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Model] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Year] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Colour] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rego] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VinNum] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EngNum] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Reg State] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GlassesValue] [float] NULL,
[PurchaseValue] [float] NULL,
[LoanPurpose] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Term] [int] NULL,
[Pay_Method] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Deposit] [float] NULL,
[First Succ Pay Date] [datetime] NULL,
[Loss Date] [datetime] NULL,
[IntRate] [float] NULL,
[Applied For] [money] NULL,
[Cash Out] [money] NULL,
[Insurance] [money] NULL,
[Application Fee] [float] NULL,
[Brokerage] [money] NULL,
[TotalInterest] [money] NULL,
[Mthly Serv Fee] [money] NULL,
[Balance] [money] NULL,
[Received] [money] NULL,
[Dishonoured] [money] NULL,
[Net Received] [money] NULL,
[Frequency] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Inst_Due] [float] NULL,
[Arrears] [float] NULL,
[NumDishon] [int] NULL,
[LodgeMonth] [datetime] NULL,
[SettleMonth] [datetime] NULL,
[Ageing] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LVR] [float] NULL,
[vehicle_age_inception] [int] NULL,
[client_address] [varchar] (2284) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [varchar] (512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[post_code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BSBNO] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account_number] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fees_charged] [float] NULL,
[interest_charged] [float] NULL,
[opening_balance] [float] NULL,
[principal_balance] [float] NULL,
[bad_debt] [money] NULL,
[arrears_2] [float] NULL,
[ageingrange1_30] [money] NULL,
[ageingrange30_60] [money] NULL,
[ageingrange60_90] [money] NULL,
[ageingrange90plus] [money] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
