CREATE TABLE [dbo].[iO_MOR_AddionalFinancingLoanDetails]
(
[MORafld_ID] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORafld_Ownership] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORafld_Version] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORafld_Sync] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORafld_Code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORafld_Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORafld_IDLink_MORafc] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORafld_LOANAMOUNT] [decimal] (18, 0) NULL,
[MORafld_PAYMENTAMOUNT] [decimal] (18, 0) NULL,
[MORafld_REQUESTEDPAYMENT] [decimal] (18, 0) NULL,
[MORafld_PAYMENTFREQUENCY] [int] NULL,
[MORafld_FIRSTPAYMENTDATE] [smalldatetime] NULL,
[MORafld_MONTHENDINDICATOR] [int] NULL,
[MORafld_ACCELERATEDPAYMENTIND] [bit] NULL,
[MORafld_INTERESTADJUSTMENTDATE] [smalldatetime] NULL,
[MORafld_MATURITYDATE] [smalldatetime] NULL,
[MORafld_REPAYMENTTYPE] [int] NULL,
[MORafld_NETRATE] [decimal] (18, 0) NULL,
[MORafld_BLENDEDAMORTIZATIONIND] [bit] NULL,
[MORafld_AMORTIZATIONINMONTHS] [tinyint] NULL,
[MORafld_AMORTIZATIONINYEARS] [tinyint] NULL,
[MORafld_PRODUCTTERMINMONTHS] [tinyint] NULL,
[MORafld_PRODUCTTERMINYEARS] [tinyint] NULL,
[MORafld_PRODUCTCODE] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MORafld_PREPAYMENTOPTION] [int] NULL,
[MORafld_EARLYPAYOUTOPTION] [int] NULL,
[MORafld_CASHBACKPERCENTAGE] [int] NULL,
[MORafld_RATECOMPOUNDINGFREQUENCY] [int] NULL,
[MORafld_RATECHANGEFREQUENCY] [int] NULL,
[MORafld_ADJUSTMENT] [decimal] (18, 0) NULL,
[MORafld_ADJUSTMENTREASON] [int] NULL,
[MORafld_ADJUSTMENTBUYDOWN] [decimal] (18, 0) NULL,
[MORafld_BUYDOWNAMOUNT] [decimal] (18, 0) NULL
) ON [PRIMARY]
GO
